tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "asdf"
brew "bat"
brew "chezmoi"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "htop"
brew "jq"
brew "lazygit"
brew "tree-sitter"
brew "neovim"
brew "rnr"
brew "starship"
brew "tmux"
brew "tmuxinator"
brew "tree"

cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"

if OS.mac?
  tap "aws/tap"
  tap "cybozu/assam" 
  tap "koekeishiya/formulae"
  tap "benbjohnson/litestream"
  tap "heroku/brew"
  tap "homebrew/bundle"
  tap "nektos/tap"
  tap "planetscale/tap"

  cask_args appdir: "/Applications"
  cask "1password"
  cask "1password-cli"
  cask "alacritty"
  cask "bettertouchtool"
  cask "charles"
  cask "cyberduck"
  cask "docker"
  cask "dropbox"
  cask "google-chrome"
  cask "google-japanese-ime"
  cask "insomnia"
  cask "jetbrains-toolbox"
  cask "karabiner-elements"
  cask "kindle"
  cask "libreoffice"
  cask "licecap"
  cask "ngrok"
  cask "obsidian"
  cask "raycast"
  cask "session-manager-plugin"
  cask "slack"
  cask "spotify"
  cask "steam"
  cask "tunnelblick"
  cask "via"
  cask "visual-studio-code"

  brew "git"
  brew "mysql" 
  brew "mysql-client" 
  brew "openjdk@11"
  brew "pandoc"
  brew "mas" 
  brew "wireshark"
  brew "postgresql@14"
  brew "nkf"
  brew "watch"
  brew "wget"
  brew "act"
  brew "ansible"
  brew "awscli"
  brew "awslogs"
  brew "deno"
  brew "flyctl"
  brew "go"
  brew "k6"
  brew "pipx"
  brew "ripgrep"
  brew "rustup-init"
  brew "wasm-pack"
  brew "aws/tap/copilot-cli"
  brew "benbjohnson/litestream/litestream"
  brew "heroku/brew/heroku"
  brew "planetscale/tap/pscale"
  brew "cybozu/assam/assam"
  brew "koekeishiya/formulae/skhd"
  brew "koekeishiya/formulae/yabai"

  mas "BetterSnapTool", id: 417375580
  mas "LINE", id: 539883307
  mas "Microsoft Excel", id: 462058435
  mas "Microsoft PowerPoint", id: 462062816
  mas "Microsoft Word", id: 462054704
  mas "Tailscale", id: 1475387142
end
