return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "fish",
        "vimdoc",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "prisma",
        "python",
        "query",
        "regex",
        "ruby",
        "rust",
        "scss",
        "svelte",
        "sql",
        "go",
        "graphql",
        "tsx",
        "typescript",
        "terraform",
        "toml",
        "vim",
        "yaml",
      },
    },
  },
}
