[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
stype = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
stype = "BoldItalic"

[font.italic]
family = "Hack Nerd Font"
stype = "MediumItalic"

[font.normal]
family = "Hack Nerd Font"

[scrolling]
history = 10000

[shell]
program = "/opt/homebrew/bin/fish"

[window]
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"
