[font]
size = 13

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[scrolling]
history = 10000

[shell]
program = "/opt/homebrew/bin/fish"

[window]
opacity = 1
decorations = "None"
dynamic_padding = true
